### ISSUE TITLE
L1.2 Risk Analysis

### ISSUE THREAD

**Issue by ketilt** [KSSno/Klimakverna#1]
[Link to main ROS](https://docs.google.com/spreadsheets/d/10q80xyg_KgIiRzDymLeaw7Tg9F_LEG0LapVtw0mR9k4/edit?usp=sharing)
[Link to all risk analyses](https://drive.google.com/drive/u/0/folders/1sBpNTKpWZQb4JoNSpqYwX2vb3CvvKuOs)

### Subtasks
- [ ] Look over existing lists and brainstorm and add draft rows for anything not covered
- [ ] Ask work package leaders and other participants for risks that they identify
  - [ ] Discuss in AP1 meeting
  - [ ] Discuss in AP3 kickoff
  - [ ] Consider discussing in AP4 kickoff (a bit early?)
- [ ] Turn draft rows into finished rows
  - [ ] Look over some examples of ROS documents as a guide for how to write
  - [ ] Ask [someone] to review the risk analysis
