### ISSUE TITLE
L1.1 Communication Plan

### ISSUE THREAD

**Issue by ketilt** [KSSno/Klimakverna#2]
[Link to document](https://docs.google.com/document/d/1YgA7oDL9NKW3RFMoJdo0fnKSVjSpisnDg_hAqp7secs/edit?usp=sharing)

### Subtasks
- [ ] Walk through stakeholders with Anita
- [ ] Decide communication needs per stakeholder
- [ ] Write a structured document
